config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    get "react_post"
    collection do
      get "react_comment"
      post "create_comment"
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  acts_as_votable
	belongs_to :user
	belongs_to :post
  validates_presence_of :description
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments

  validates_presence_of :title, :description
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  acts_as_voter
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit update create destroy react_post react_comment]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def create_comment
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post), notice: "Comment was successfully created." 
    else
      redirect_to post_url(@comment.post), alert: "Fail to create comment." 
    end
  end

  def react_post
    @post = Post.find_by(id: params[:post_id])
    if params[:reaction] == 'liked'
      @post.liked_by current_user
    elsif params[:reaction] == 'disliked'
      @post.unliked_by current_user
    end
    redirect_to post_url(@post), notice: "Post was successfully #{params[:reaction]}." 
  end

  def react_comment
    comment = Comment.find_by(id: params[:comment_id])
    if params[:reaction] == 'liked'
      comment.liked_by current_user
    elsif params[:reaction] == 'disliked'
      comment.unliked_by current_user
    end
    redirect_to post_url(comment.post), notice: "Comment was successfully #{params[:reaction]}." 
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :user_id)
    end

    def comment_params
      params.require(:comment).permit(:description, :user_id, :post_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-primary"><%= notice %></p>
    <% elsif alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_comment.html.erb
<li class="list-group-item">
  <strong><%= comment.user.email %></strong>
  <p class="mb-0"><%= comment.description %></p>
	<p><%= comment.get_likes.size %> Likes</p>
	<div>
		<% if current_user && current_user.liked?(comment) %>
			<%= link_to 'Dislike Comment', react_comment_posts_path(comment_id: comment.id, reaction: 'disliked'), class: "btn btn-outline-danger" %>
		<% else %>
			<%= link_to 'Like Comment', react_comment_posts_path(comment_id: comment.id, reaction: 'liked'), class: "btn btn-outline-primary" %>
		<% end %>
	</div>
</li>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row my-3">
    <div class="col-md-2">
      <%= form.label :title %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :title %>
    </div>
  </div>

  <div class="row my-3">
    <div class="col-md-2">
      <%= form.label :description %>
    </div>

    <div class="col-md-10">
      <%= form.text_area :description, rows: 3, class: "w-50" %>
    </div>
  </div>
  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Home Page</h1>

<% if user_signed_in? %>
  <h5>
    <%= current_user.email %> signed in
  </h5>
  <%= link_to 'Edit Details', edit_user_registration_path, class: 'px-3' %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'px-3' %>
<% else %>
  <%= link_to 'Sign In', user_session_path %>
  <%= link_to 'Register', new_user_registration_path, class: 'px-3' %>
<% end %>



<h1 class="mt-5">Posts</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>User</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.description, length: 30) %></td>
        <td><%= post.user.email %></td>
        <td>
          <%= link_to 'Show', post, class: "mx-3" %>
          <% if current_user && post.user_id == current_user.id %>
            <%= link_to 'Edit', edit_post_path(post), class: "mx-3" %>
            <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "mx-3" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>
<p><%= @post.get_likes.size %> Likes</p>
<div>
  <% if current_user && current_user.liked?(@post) %>
    <%= link_to 'Dislike', post_react_post_path(post_id: @post.id, reaction: 'disliked'), class: "btn btn-danger" %>
  <% else %>
    <%= link_to 'Like', post_react_post_path(post_id: @post.id, reaction: 'liked'), class: "btn btn-primary" %>
  <% end %>
</div>
<% if current_user && @post.user_id == current_user.id %>
  <div>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary my-2" %>
  </div>
<% end %>


<h2 class="mt-3">Comments</h2>
<div>
  <ul class="list-group w-50">
    <%= render partial: 'comment', collection: @post&.comments, as: :comment %>
  </ul>
</div>


<% if user_signed_in? %>
  <h3 class="mt-3">New Comment</h3>
  <div>
    <%= form_for @comment, as: :comment, url: create_comment_posts_path do |form| %>
      <div class="my-1">
        <div>
          <%= form.label 'Comment:' %>
        </div>
        <div>
          <%= form.text_area :description, rows: 3, class: "w-50" %>
        </div>
      </div>
      <div class="field">
        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :post_id, value: @post.id %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>

<% else %>
  <%= link_to 'Sign In To Create Comment', user_session_path, class: "btn btn-secondary my-3" %><br>
<% end %>


<%= link_to 'Back', posts_path, class: "btn btn-dark" %>